### ISSUE TITLE
Filter by tag

### ISSUE THREAD

**Issue by caipng** [AY2122S1-CS2103-W14-3/tp#26] opened 2021-09-08 07:19 UTC
### User Story

As a user, I can filter my students by tags, so that I will only see contacts relevant to what I am doing currently.

**Comment by caipng** [comment] 2021-11-03 10:44
This is good to have, but not crucial to our app. Closing due to lack of time to implement.

**Comment by FergusMok** [comment] 2021-11-03 15:00
Duplicate of #171

**Closed by FergusMok** 2021-11-03 15:00 UTC
Labels: type.Story, priority.Low
